---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-13.10

suites:
  - name: default
    run_list:
      - "recipe[neo4j-docker]"
    attributes:
      neo4j:
        config:
          cache_type: none
